
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Random;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class Main extends javax.swing.JFrame {

    MyThread threadWest = null;
    MyThread threadEast = null;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        threadEast = new MyThread(jTextAreaEast);
        threadWest = new MyThread(jTextAreaWest);

        this.setTitle("StopResume");
        this.addWindowListener(new MyClosingWindow());
        this.setSize(900, 477);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWest = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaWest = new javax.swing.JTextArea();
        jButtonWest = new javax.swing.JButton();
        jPanelEast = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaEast = new javax.swing.JTextArea();
        jButtonEast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanelWest.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaWest.setColumns(20);
        jTextAreaWest.setRows(5);
        jScrollPane1.setViewportView(jTextAreaWest);

        jPanelWest.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonWest.setText("Go");
        jButtonWest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWestActionPerformed(evt);
            }
        });
        jPanelWest.add(jButtonWest, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelWest);

        jPanelEast.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaEast.setColumns(20);
        jTextAreaEast.setRows(5);
        jScrollPane2.setViewportView(jTextAreaEast);

        jPanelEast.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButtonEast.setText("Go");
        jButtonEast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEastActionPerformed(evt);
            }
        });
        jPanelEast.add(jButtonEast, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelEast);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonWestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWestActionPerformed
        if (jButtonWest.getText().equals("Go")) {
            jButtonWest.setText("Suspend");
            if (!(threadWest.isAlive())) {
                threadWest.start();
            }
            else 
                threadWest.resumeThread();
        } else {
            jButtonWest.setText("Go");
            threadWest.stopThread(); 
        }
    }//GEN-LAST:event_jButtonWestActionPerformed

    private void jButtonEastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEastActionPerformed
        if (jButtonEast.getText().equals("Go")) {
            jButtonEast.setText("Suspend");
            if (!(threadEast.isAlive())) {
                threadEast.start();
            }
            else 
                threadEast.resumeThread();
        } else {
            jButtonEast.setText("Go");
            threadEast.stopThread(); 
        }
    }//GEN-LAST:event_jButtonEastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEast;
    private javax.swing.JButton jButtonWest;
    private javax.swing.JPanel jPanelEast;
    private javax.swing.JPanel jPanelWest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaEast;
    private javax.swing.JTextArea jTextAreaWest;
    // End of variables declaration//GEN-END:variables

    private class MyClosingWindow extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent e) {
            int r = JOptionPane.showConfirmDialog(Main.this, "Are you sure?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
            if (r == JOptionPane.OK_OPTION) {
                Main.this.dispose();
                System.exit(0);
            }
        }
    }

}
