
import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class Main extends javax.swing.JFrame {
    DefaultListModel<Person> model;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        loadSizeComboBox();
        this.setTitle("Persons");
        this.setSize(750, 555);
        this.setLocationRelativeTo(null);
        
        model = new DefaultListModel<>();
        jListPersons.setCellRenderer(new MyListCellRenderer());
        jListPersons.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorth = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPersons = new javax.swing.JList<>();
        jPanelSouth = new javax.swing.JPanel();
        jSliderHeight = new javax.swing.JSlider();
        jSliderWeight = new javax.swing.JSlider();
        jPanelSouthSouth = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelSize = new javax.swing.JLabel();
        jComboBoxSize = new javax.swing.JComboBox<>();
        jButtonAddPerson = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanelNorth.setLayout(new java.awt.BorderLayout());

        jListPersons.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jListPersons);

        jPanelNorth.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelNorth);

        jPanelSouth.setLayout(new java.awt.GridLayout(3, 1));

        jSliderHeight.setMajorTickSpacing(5);
        jSliderHeight.setMaximum(200);
        jSliderHeight.setMinimum(100);
        jSliderHeight.setMinorTickSpacing(1);
        jSliderHeight.setPaintLabels(true);
        jSliderHeight.setPaintTicks(true);
        jSliderHeight.setSnapToTicks(true);
        jSliderHeight.setToolTipText("");
        jSliderHeight.setValue(150);
        jSliderHeight.setAutoscrolls(true);
        jSliderHeight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Height [cm]"));
        jSliderHeight.setName(""); // NOI18N
        jPanelSouth.add(jSliderHeight);

        jSliderWeight.setMajorTickSpacing(10);
        jSliderWeight.setMaximum(120);
        jSliderWeight.setMinimum(40);
        jSliderWeight.setMinorTickSpacing(2);
        jSliderWeight.setPaintLabels(true);
        jSliderWeight.setPaintTicks(true);
        jSliderWeight.setSnapToTicks(true);
        jSliderWeight.setValue(80);
        jSliderWeight.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Weight [kg]"));
        jPanelSouth.add(jSliderWeight);

        jPanelSouthSouth.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 33));

        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelName.setText("Name:");
        jPanel1.add(jLabelName);

        jTextFieldName.setColumns(20);
        jPanel1.add(jTextFieldName);

        jLabelSize.setText("Size:");
        jPanel1.add(jLabelSize);

        jPanel1.add(jComboBoxSize);

        jButtonAddPerson.setText("Add person");
        jButtonAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPersonActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddPerson);

        jPanelSouthSouth.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 33));

        jButtonExit.setText("Exit");
        jButtonExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonExit);

        jPanelSouthSouth.add(jPanel2, java.awt.BorderLayout.EAST);

        jPanelSouth.add(jPanelSouthSouth);

        getContentPane().add(jPanelSouth);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPersonActionPerformed
        Person p = new Person(jTextFieldName.getText(), jSliderHeight.getValue(), jSliderWeight.getValue(), (Size)jComboBoxSize.getSelectedItem());
        ((DefaultListModel<Person>)jListPersons.getModel()).addElement(p);
        jTextFieldName.setText("");
    }//GEN-LAST:event_jButtonAddPersonActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private void loadSizeComboBox(){
        jComboBoxSize.addItem(Size.XS);
        jComboBoxSize.addItem(Size.S);
        jComboBoxSize.addItem(Size.M);
        jComboBoxSize.addItem(Size.L);
        jComboBoxSize.addItem(Size.XL);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPerson;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JComboBox<Size> jComboBoxSize;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JList<Person> jListPersons;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPanel jPanelSouthSouth;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSliderHeight;
    private javax.swing.JSlider jSliderWeight;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    private static class MyListCellRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus ) {
            Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (((Person)value).getSize() == Size.XS) {
                c.setBackground(Color.GREEN);
            }
            if (((Person)value).getSize() == Size.XL){
                c.setBackground(Color.RED);
            }
            return c;
        }
    }

}
